# Basic Site Settings

locale: "en-US"
site_theme: "default"

title: "Tanushri Bhise"
name: "Tanushri Bhise"
description: "AI & Data Science Student | Aspiring Software Engineer"

url: "https://tanushri-bhise.github.io"
baseurl: ""

repository: "TANUSHRI-BHISE/TANUSHRI-BHISE.github.io"

# Author Info

author:
avatar: "profile.png"
name: "Tanushri Bhise"
bio: "3rd Year AI & Data Science student passionate about coding and problem solving"
location: "Pune, India"
email: "[your-email@gmail.com](mailto:your-email@gmail.com)"

github: "TANUSHRI-BHISE"
linkedin: ""
instagram: ""

# Site Settings

breadcrumbs: false
read_more: "disabled"

# Collections

collections:
portfolio:
output: true
permalink: /:collection/:path/

# Defaults

defaults:

* scope:
  path: ""
  type: pages
  values:
  layout: single
  author_profile: true

# Plugins

plugins:

* jekyll-feed
* jekyll-sitemap
